### GET /
GET http://localhost:8000

### Register User to the /auth/register endpoint
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username":"clown123@gmmail.com",
    "password":"password123"
}

### login user  to the /auth/login endpoint
POST http://localhost:8080/auth/login
